services:
  tests:
    build:
      context: .
      dockerfile: docker/testing/Dockerfile
    image: messenger-test-web-app

    command: ["php", "artisan", "test", "--env=testing" ]

    ports:
      - 8080:80

    depends_on:
      db:
        condition: service_healthy
      chat-events-queue:
        condition: service_healthy

    user: "vodev:www-data"

    volumes:
      - ./:/var/www
      - ./.env.testing:/var/www/.env
      - ./.env.testing:/var/www/.env.testing
      - ./docker/mysql_custom.cnf:/etc/mysql/conf.d/mysql_custom.cnf:ro

    networks:
      - backend-test

  chat-events-queue:
    build:
      context: .
      dockerfile: docker/testing/Dockerfile
    image: messenger-dev-web-app

    entrypoint: docker/entrypoints/queue

    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "./docker/healthchecks/tq"]
      interval: 10s
      timeout: 5s
      retries: 5

    user: "vodev:www-data"

    volumes:
      - ./:/var/www
      - ./docker/mysql_custom.cnf:/etc/mysql/conf.d/mysql_custom.cnf:ro
      - ./.env.testing:/var/www/.env
    networks:
      - backend-test

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8025" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 8855:8025
      - 1155:1025
    networks:
      - backend-test
    depends_on:
      tests:
        condition: service_started
  db:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: messengerdb_testing
      LANG: C.UTF_8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - backend-test-data:/var/lib/mysql/
    networks:
      - backend-test

networks:
  backend-test:
volumes:
  backend-test-data:
