#!/bin/bash

php artisan view:clear
php artisan route:clear
php artisan config:clear
php artisan cache:clear
php artisan key:generate --force
php artisan jwt:secret
php artisan migrate:fresh --seed

exec "$@"